apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: browsers-api-pdb
  namespace: browsers-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: browsers-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: browsers-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgres
